# workflow to show how to develop workflows in new branches
name: Develop in a branch

on: [pull_request, workflow_dispatch]

jobs:
  job1:
    permissions: 
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Workflow triggered in branch '${{ github.ref }}'."
          echo "Workflow triggered by event '${{ github.event_name }}'."
          echo "Workflow triggered by actor '${{ github.actor }}'."
          echo "PR title is '${{ github.event.pull_request.title }}'."
      - run: |
          echo "::notice file=.github/workflows/DevelopInBranch.yml,line=19,col=11,endColumn=51::There is a debug message that is not always visible!"
          echo "::warning file=.github/workflows/DevelopInBranch.yml,line=19,endline=21::A lot of messages"
          echo "::error title=Script Injection,file=.github/workflows/DevelopInBranch.yml,line=17,col=34,endColumn=65::Potential script injection"
      - uses: actions/checkout@v4.2.2
      - uses: devops-actions/actionlint@v0.1.2